import axios from "axios";
import { useState } from "react";
import { jsPDF } from "jspdf";

function App() {
  const [text, setText] = useState("");
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [image, setImage] = useState(null);
  const [sourceUrl, setSourceUrl] = useState("");
  const currentDate = new Date().toLocaleString();

  const analyzeContent = async () => {
  try {
    const res = await axios.post(
  "http://127.0.0.1:8000/analyze",
  {
    text,
    sourceUrl,
  }
);


console.log(res.data);

setResult(res.data);

setHistory((prev) => [
  text,
  ...prev.slice(0, 4),
]);
  } catch (error) {
    console.log(error);
  }
};

const downloadReport = () => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text("TruthLens AI Verification Report", 20, 20);

  doc.setFontSize(12);

  doc.text(`Generated: ${currentDate}`, 20, 30);

  doc.text(`Trust Score: ${result.trustScore}/100`, 20, 40);
  doc.text(`Risk Level: ${result.riskLevel}`, 20, 50);
  doc.text(`AI Confidence: ${result.confidence}%`, 20, 60);
  doc.text(
  `Source Credibility: ${result.sourceCredibility}`,
  20,
  70
);

doc.text(`Source URL: ${sourceUrl}`, 20, 80);

doc.text("Reasons:", 20, 110);

let y = 120;

if (result.reasons.length === 0) {
  doc.text(
    "No suspicious indicators detected.",
    25,
    y
  );
  y += 10;
}

result.reasons.forEach((reason) => {
  doc.text(`• ${reason}`, 25, y);
  y += 10;
});

  doc.text(
    "Generated by TruthLens AI • ASEEV Verification Framework",
    20,
    y + 20
  );

  doc.save("TruthLens_Report.pdf");
};

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#0f172a",
        color: "white",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        paddingTop: "80px",
      }}
    >
      <h1 style={{ fontSize: "4rem" }}>TruthLens AI</h1>

      <p
        style={{
          color: "#94a3b8",
          marginBottom: "30px",
        }}
      >
        Verify Before You Trust
      </p>
      <input
  type="file"
  accept="image/*"
  onChange={(e) => setImage(e.target.files[0])}
      />

      {image && (
  <img
    src={URL.createObjectURL(image)}
    alt="Preview"
    width="300"
    style={{
      marginTop: "20px",
      marginBottom: "20px",
      borderRadius: "10px",
      border: "2px solid white",
    }}
  />
)}

      <input
  type="text"
  placeholder="Enter Source URL (Optional)"
  value={sourceUrl}
  onChange={(e) => setSourceUrl(e.target.value)}
  style={{
    width: "500px",
    padding: "10px",
    marginBottom: "20px",
    borderRadius: "8px",
  }}
/>
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Paste news article or text here..."
        rows="10"
        cols="70"
        style={{
          padding: "15px",
          borderRadius: "10px",
        }}
      />

      <button
  onClick={analyzeContent}
  style={{
    marginTop: "20px",
    padding: "12px 30px",
    borderRadius: "10px",
    cursor: "pointer",
  }}
>
  Analyze Content
</button>
{result && (
  <div
    style={{
      marginTop: "40px",
      width: "700px",
      background: "#111827",
      borderRadius: "15px",
      padding: "25px",
      color: "white",
      boxShadow: "0 0 20px rgba(0,0,0,0.3)",
    }}
  >
    <h2
      style={{
        textAlign: "center",
        marginBottom: "20px",
      }}
    >
      Content Credibility Report
    </h2>

    <div
  style={{
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "25px",
  }}
>
  <div>
    <h4>AI Confidence</h4>
    <h2>{result.confidence}%</h2>
  </div>

  <div>
    <h4>Source Credibility</h4>
    <h2>{result.sourceCredibility}</h2>
  </div>

  <div>
    <h4>Image Authenticity</h4>
<h2>{image ? "82%" : "Not Analyzed"}</h2>
  </div>
</div>

    <div
      style={{
        display: "flex",
        justifyContent: "space-around",
        marginBottom: "25px",
      }}
    >
      <div>
  <h3>Trust Score</h3>

  <h1
  style={{
    fontSize: "4rem",
    margin: 0,
  }}
>
  {result.trustScore}/100
</h1>

  <div
    style={{
      width: "200px",
      height: "12px",
      background: "#374151",
      borderRadius: "20px",
      overflow: "hidden",
      marginTop: "10px",
    }}
  >
    <div
      style={{
        width: `${result.trustScore}%`,
        height: "100%",
        background: "#22c55e",
      }}
    />
  </div>
</div>

      <div>
        <h3>Risk Level</h3>
        <h1
          style={{
            color:
              result.riskLevel === "Low"
                ? "#22c55e"
                : "#ef4444",
          }}
        >
          {result.riskLevel}
        </h1>
      </div>
    </div>

    <div
  style={{
    marginTop: "20px",
  }}
>
  <h3>Trust Heatmap</h3>

  <p>Authenticity</p>

  <div
    style={{
      width: "100%",
      height: "12px",
      background: "#374151",
      borderRadius: "10px",
    }}
  >
    <div
      style={{
        width: `${result.trustScore}%`,
        height: "100%",
        background: "#22c55e",
      }}
    />
  </div>

  <p style={{ marginTop: "15px" }}>
    Credibility
  </p>

  <div
    style={{
      width: "100%",
      height: "12px",
      background: "#374151",
      borderRadius: "10px",
    }}
  >
    <div
      style={{
        width: `${result.trustScore - 5}%`,
        height: "100%",
        background: "#3b82f6",
      }}
    />
  </div>
</div>

    <div
      style={{
        marginTop: "20px",
      }}
    >
      <h3>AI Verdict</h3>

      <p
  style={{
    color:
      result.riskLevel === "Low"
        ? "#22c55e"
        : result.riskLevel === "Medium"
        ? "#f59e0b"
        : "#ef4444",
    fontWeight: "bold",
    fontSize: "20px",
  }}
>
  {result.prediction}
</p>

      <p
        style={{
          fontSize: "20px",
          fontWeight: "bold",
        }}
      >
        {result.prediction}
      </p>
    </div>

    <div
      style={{
        marginTop: "25px",
      }}
    >
      <h3>AI Explanation</h3>

<ul
  style={{
    listStyle: "none",
    padding: 0,
  }}
>
  {result.reasons.map((reason, index) => (
    <li key={index}>
      ✓ {reason}
    </li>
  ))}
</ul>

<button
  onClick={downloadReport}
  style={{
    marginTop: "20px",
    padding: "12px 25px",
    borderRadius: "10px",
    cursor: "pointer",
    background: "#22c55e",
    color: "white",
    border: "none",
    fontWeight: "bold",
  }}
>
  📄 Download Verification Report
</button>

      
    </div>

    <div
  style={{
    marginTop: "25px",
  }}
>
  <h3>TruthLens ASEEV Framework</h3>

  <ul
    style={{
      listStyle: "none",
      padding: 0,
    }}
  >
    <li>🔍 Analyze Content</li>
    <li>📊 Score Credibility</li>
    <li>⚖ Evaluate Risk</li>
    <li>💡 Explain Findings</li>
    <li>✅ Verify Information</li>
  </ul>
</div>
  </div>
)}
   {history.length > 0 && (
  <div
    style={{
      marginTop: "40px",
      width: "700px",
      background: "#111827",
      padding: "20px",
      borderRadius: "15px",
    }}
  >
    <h3>Recent Verifications</h3>

    <ul
      style={{
        listStyle: "none",
        padding: 0,
      }}
    >
      {history.map((item, index) => (
        <li key={index}>
          ✓ {item}
        </li>
      ))}
    </ul>
  </div>
)}

<p
  style={{
    marginTop: "30px",
    color: "#94a3b8",
    fontSize: "14px",
  }}
>
  Powered by TruthLens AI • ASEEV Verification Framework
</p>

<p
  style={{
    marginTop: "15px",
    color: "#94a3b8",
    fontSize: "12px",
  }}
>
  Results are AI-assisted estimates and should be independently verified.
</p>
    </div>
  );
}

export default App;